name: All Tests (Master)
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: "Run unit tests (build tag: unit)"
        run: go test -v -tags=unit ./...
      - name: "Run integration tests (build tag: integration)"
        run: go test -v -tags=integration ./...
