            - name: Go Test Action
  # You may pin to the exact commit or the version.
  # uses: robherley/go-test-action@a612d1675dda7397d3bced585f8a2a3a8545455f
  uses: robherley/go-test-action@v0.4.1,
  with:
    # Directory of go module to test
    moduleDirectory: # optional, default is .
    # Arguments to `go test`, `-json` will be prepended
    testArguments: "./... -run '^TestCalculatePace$' -v"
    # Parse the specified JSON file, instead of executing go test
    fromJSONFile: # optional
    # Whitespace separated list of renderable items to omit. See README.md for details.
    omit: # optional
    # Omit any packages from summary output that do not have tests
    omitUntestedPackages: # optional, default is false
    # Omit the pie chart from the summary output
    omitPie: # optional, default is false
    # Omit any packages from summary output that are successful
    omitSuccessfulPackages: # optional, default is false
          
